### ISSUE TITLE
key not found: OUTSIDE

### ISSUE THREAD

**Issue by wlyu** [didi/Logi-KafkaManager#221]
`[31merror[0m] k.m.m.ActorModel$BrokerIdentity$ - Failed to parse endpoint : OUTSIDE://kafka-3:30013
java.util.NoSuchElementException: key not found: OUTSIDE
	at scala.collection.MapLike$class.default(MapLike.scala:228) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractMap.default(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at scala.collection.AbstractMap.apply(Map.scala:59) ~[org.scala-lang.scala-library-2.11.8.jar:na]
	at kafka.manager.model.SecurityProtocol$.apply(model.scala:410) ~[kafka-manager.kafka-manager-1.3.3.11-sans-externalized.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:262) ~[kafka-manager.kafka-manager-1.3.3.11-sans-externalized.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7$$anonfun$apply$7.apply(ActorModel.scala:259) ~[kafka-manager.kafka-manager-1.3.3.11-sans-externalized.jar:na]
	at scalaz.Validation$.fromTryCatchNonFatal(Validation.scala:397) ~[org.scalaz.scalaz-core_2.11-7.2.4.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:259) [kafka-manager.kafka-manager-1.3.3.11-sans-externalized.jar:na]
	at kafka.manager.model.ActorModel$BrokerIdentity$$anonfun$6$$anonfun$apply$6$$anonfun$7.apply(ActorModel.scala:258) [kafka-manager.kafka-manager-1.3.3.11-sans-externalized.jar:na]
`

**Comment by ZQKC** [comment]
进行什么操作，然后出现这个错误的？辛苦描述的具体详细一些
