### ISSUE TITLE
1.0版本server采样带有header的topic消息，出现异常

### ISSUE THREAD

**Issue by devin-df** [didi/Logi-KafkaManager#328]
kafka-manager自己的报错如下：
o.apache.kafka.clients.consumer.internals.Fetcher - Unknown error fetching data for topic-partition *****
kafka-server报错如下：
ERROR [ReplicaManager broker=0] Error processing append operation on partition **********
  (kafka.server.ReplicaManager)
java.lang.IllegalArgumentException: Magic v1 does not support record headers
 at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:403)
 at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:586)
 at org.apache.kafka.common.record.AbstractRecords.convertRecordBatch(AbstractRecords.java:134)
 at org.apache.kafka.common.record.AbstractRecords.downConvert(AbstractRecords.java:109)
 at org.apache.kafka.common.record.FileRecords.downConvert(FileRecords.java:253)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$convertedPartitionData$1$1$$anonfun$apply$4.apply(KafkaApis.scala:520)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$convertedPartitionData$1$1$$anonfun$apply$4.apply(KafkaApis.scala:518)
 at scala.Option.map(Option.scala:146)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$convertedPartitionData$1$1.apply(KafkaApis.scala:518)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$convertedPartitionData$1$1.apply(KafkaApis.scala:508)
 at scala.Option.flatMap(Option.scala:171)
 at kafka.server.KafkaApis.kafka$server$KafkaApis$$convertedPartitionData$1(KafkaApis.scala:508)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$createResponse$2$1.apply(KafkaApis.scala:556)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$createResponse$2$1.apply(KafkaApis.scala:555)
 at scala.collection.Iterator$class.foreach(Iterator.scala:891)
 at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
 at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
 at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
 at kafka.server.KafkaApis.kafka$server$KafkaApis$$createResponse$2(KafkaApis.scala:555)
 at kafka.server.KafkaApis$$anonfun$kafka$server$KafkaApis$$fetchResponseCallback$1$1.apply(KafkaApis.scala:569)

**Comment by ZQKC** [comment]
![image](https://user-images.githubusercontent.com/4694454/122497251-b1c56780-d01f-11eb-9f03-a891b2a146cf.png)

原因一：1.0版本的Kafka没有在这块做好兼容，1.1版本对这块进行兼容优化，导致低版本客户端消费的时候，出现了请求失败的情况。
原因二：Logi-KM使用的Kafka客户端的版本是0.10.2的，近期也在考虑进行客户端版本升级，但是因为牵扯到高低版本客户端的一些接口没了或者是scala语法变了，因此这个升级客户端的版本估计会持续一小段时间才可以对外发布。

**Comment by ZQKC** [comment]
无更多反馈则关闭该issue
