### ISSUE TITLE
请求pending问题

### ISSUE THREAD

**Issue by Huyueeer** [didi/Logi-KafkaManager#330]
各种请求偶尔会发生长时间的pending情况，例如删除请求在pending一分钟后报错，查询日志发现以下错误：
```
2021-06-18 04:37:32.339 [Collect-Metrics-Thread-1-216] ERROR c.x.k.manager.service.service.impl.JmxServiceImpl - get attributes failed, metrics:TopicMetrics{appId='null', cluste
rId=8, topicName='xxxxx_topic', metricsMap={}} objectName:kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=xxxxx_topic.
java.io.IOException: Connection closed
        at javax.management.remote.rmi.RMIConnector.getMBeanServerConnection(RMIConnector.java:400)
        at javax.management.remote.rmi.RMIConnector.getMBeanServerConnection(RMIConnector.java:389)
        at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.getAttributes(JmxConnectorWrap.java:125)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getAndSupplyAttributes2BaseMetrics(JmxServiceImpl.java:263)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getTopicMetrics(JmxServiceImpl.java:171)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getTopicMetrics(JmxServiceImpl.java:130)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl$1.call(JmxServiceImpl.java:93)
        at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl$1.call(JmxServiceImpl.java:90)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ZQKC** [comment]
> 各种请求偶尔会发生长时间的pending情况，例如删除请求在pending一分钟后报错，查询日志发现以下错误：
> 
> ```
> 2021-06-18 04:37:32.339 [Collect-Metrics-Thread-1-216] ERROR c.x.k.manager.service.service.impl.JmxServiceImpl - get attributes failed, metrics:TopicMetrics{appId='null', cluste
> rId=8, topicName='xxxxx_topic', metricsMap={}} objectName:kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=xxxxx_topic.
> java.io.IOException: Connection closed
>         at javax.management.remote.rmi.RMIConnector.getMBeanServerConnection(RMIConnector.java:400)
>         at javax.management.remote.rmi.RMIConnector.getMBeanServerConnection(RMIConnector.java:389)
>         at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.getAttributes(JmxConnectorWrap.java:125)
>         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getAndSupplyAttributes2BaseMetrics(JmxServiceImpl.java:263)
>         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getTopicMetrics(JmxServiceImpl.java:171)
>         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getTopicMetrics(JmxServiceImpl.java:130)
>         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl$1.call(JmxServiceImpl.java:93)
>         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl$1.call(JmxServiceImpl.java:90)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)
> ```

这个错误是获取JMX失败的错误，这块是删除什么导致的这个错误呢？一般删除数据应该不会走到这个逻辑

**Comment by Huyueeer** [comment]
> > 各种请求事件会发生长时间的等待情况，例如删除请求在等待一分钟后报错，日志发现以下错误：
> > ```
> > 2021-06-18 04:37:32.339 [Collect-Metrics-Thread-1-216] ERROR c.x.k.manager.service.service.impl.JmxServiceImpl - get attributes failed, metrics:TopicMetrics{appId='null', cluste
> > rId=8, topicName='xxxxx_topic', metricsMap={}} objectName:kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=xxxxx_topic.
> > java.io.IOException: Connection closed
> >         at javax.management.remote.rmi.RMIConnector.getMBeanServerConnection(RMIConnector.java:400)
> >         at javax.management.remote.rmi.RMIConnector.getMBeanServerConnection(RMIConnector.java:389)
> >         at com.xiaojukeji.kafka.manager.common.utils.jmx.JmxConnectorWrap.getAttributes(JmxConnectorWrap.java:125)
> >         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getAndSupplyAttributes2BaseMetrics(JmxServiceImpl.java:263)
> >         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getTopicMetrics(JmxServiceImpl.java:171)
> >         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl.getTopicMetrics(JmxServiceImpl.java:130)
> >         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl$1.call(JmxServiceImpl.java:93)
> >         at com.xiaojukeji.kafka.manager.service.service.impl.JmxServiceImpl$1.call(JmxServiceImpl.java:90)
> >         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> >         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> >         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> >         at java.lang.Thread.run(Thread.java:748)
> > ```
> 
> 这个错误是获取JMX失败的错误，这块是删除什么导致的这个错误呢？一般删除数据应该不会看到逻辑

**Comment by ZQKC** [comment]
这块还有更多信息么？没有的话将关闭该issue
